//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// script.rc で使用
//
#define IDD_DIALOG4                     118
#define IDR_MENU3                       120
#define IDB_BITMAP1                     123
#define IDD_DIALOG1                     124
#define IDR_MENU1                       125
#define IDB_BITMAP2                     128
#define IDC_MESSAGE                     1000
#define IDC_TEXT_ABOUTTITLE             1001
#define IDC_NAME                        1002
#define IDC_COMBO_CHANNEL               1003
#define IDC_VERSION                     1004
#define IDC_COMBO_SPS                   1006
#define IDC_TEXT_FREQUENCY              1007
#define IDC_FREQUENCY_MAIN              1008
#define IDC_TEXT_HERTZ                  1009
#define IDC_VOLUME_MAIN                 1010
#define IDC_TEXT_FREQUENCY2             1011
#define IDC_TEXT_VOLUME                 1011
#define IDC_TEXT_HERTZ2                 1012
#define IDC_CHANNEL_OFFSET              1013
#define IDC_CHANNELOFFSET               1014
#define IDC_WAITSAMPLE                  1015
#define IDC_OFFSET                      1016
#define IDC_OFFSET_MAIN                 1017
#define IDC_TEXT_FREQUENCY3             1018
#define IDC_TEXT_OFFSET                 1018
#define IDC_TEXT_HERTZ3                 1019
#define IDC_TEXT_CHANNELOFFSET          1020
#define IDC_TEXT_WAITSAMPLE             1021
#define IDC_CHECK_ADDUNIT               1022
#define IDC_COMBO_TYPE_MAIN             1023
#define IDC_TEXT_FREQUENCY4             1024
#define IDC_TEXT_TYPE                   1024
#define IDC_TEXT_REVERSE                1025
#define IDC_CHECK_REVERSE_MAIN          1026
#define IDC_SAMPLESIZE                  1027
#define IDC_CHECK_REVERSE_FREQ          1028
#define IDC_SEC                         1029
#define IDC_SAMPLENUM                   1030
#define IDC_CHECK_REVERSE_MAIN3         1031
#define IDC_CHECK_REVERSE_VOLUME        1032
#define IDC_CHECK_ENABLE                1033
#define IDC_ENVELOPE_SEC_1              1034
#define IDC_ENVELOPE_SEC_2              1035
#define IDC_TAB4                        1036
#define IDC_TAB                         1037
#define IDC_ENVELOPE_SEC_3              1038
#define IDC_SEC2                        1039
#define IDC_QUALITY                     1040
#define IDC_TEXT_PAN                    1041
#define IDC_ENVELOPE_SEC_4              1042
#define IDC_COMBO_UNIT_FROM             1043
#define IDC_COMBO_UNIT_TO               1044
#define IDC_FREQUENCY_FREQ              1045
#define IDC_TEXT_NAME                   1046
#define IDC_TEXT_HERTZ4                 1047
#define IDC_VOLUME_FREQ                 1048
#define IDC_TEXT_HERTZ5                 1049
#define IDC_TEXT_SPS                    1050
#define IDC_OFFSET_FREQ                 1051
#define IDC_TEXT_LANGE                  1052
#define IDC_TEXT_LENGTH                 1053
#define IDC_TEXT_HERTZ6                 1054
#define IDC_TEXT_SEC                    1055
#define IDC_COMBO_TYPE_FREQ             1056
#define IDC_FREQUENCY_VOLUME            1057
#define IDC_TEXT_HERTZ7                 1058
#define IDC_VOLUME_VOLUME               1059
#define IDC_TEXT_HERTZ8                 1060
#define IDC_OFFSET_VOLUME               1061
#define IDC_TEXT_HERTZ9                 1062
#define IDC_COMBO_TYPE_VOLUME           1063
#define IDC_ENVELOPE_VOL_1              1064
#define IDC_ENVELOPE_VOL_2              1065
#define IDC_TEXT_SAMPLENUM              1066
#define IDC_TEXT_SAMPLE_NUM             1066
#define IDC_TEXT_SEC2                   1067
#define IDC_TEXT_SEC_4                  1067
#define IDC_ENVELOPE_VOL_3              1068
#define IDC_TEXT_INITIALIZETITLE        1069
#define IDC_TEXT_QUALITYTITLE           1070
#define IDC_PAN                         1071
#define IDC_TEXT_SAMPLENUM2             1072
#define IDC_TEXT_WAVETITLE              1073
#define IDC_TEXT_UNITTITLE              1074
#define IDC_TEXT_SURETITLE              1075
#define IDC_TEXT_TOTALSAMPLE            1076
#define IDC_CREATOR                     1077
#define IDC_BASICKEY                    1078
#define IDC_TEXT_BASICKEY               1079
#define IDC_TEXT_HEARSELECT             1080
#define IDC_LIST                        1081
#define IDC_DIRECTORYPATH               1082
#define IDC_INFORMATION                 1083
#define IDC_CHECK_SOUND                 1084
#define IDC_TEXT_CONFIGTITLE            1085
#define IDC_TEXT_BUILD_QUALITY          1086
#define IDC_TEXT_BUILD_CHANNEL          1087
#define IDC_TEXT_BUILD_SPS              1089
#define IDC_COMBO_BUILD_CHANNEL         1090
#define IDC_COMBO_BUILD_SPS             1092
#define IDC_TEXT_AT_QUALITY             1093
#define IDC_TEXT_AT_CHANNEL             1094
#define IDC_TEXT_AT_SPS                 1096
#define IDC_TEXT_QUALITY                1096
#define IDC_COMBO_AT_CHANNEL            1097
#define IDC_COMBO_AT_SPS                1099
#define IDC_TEXT_AT_BUFFER              1100
#define IDC_TEXT_BUFFER                 1100
#define IDC_AT_BUFFER                   1101
#define IDC_TEXT_SECOND                 1102
#define IDC_COMBO_AT_DEVICE             1103
#define IDC_TEXT_AT_DEVICE              1104
#define IDC_TEXT_DEVICE                 1104
#define IDC_DEFAULT                     1105
#define IDC_BASICKEY_UP                 1106
#define IDC_BASICKEY_DOWN               1107
#define IDC_SAVE_AS                     1108
#define IDC_SAVE                        1109
#define IDC_LOAD                        1110
#define IDC_LOAD2                       1111
#define IDC_SAVE_AS2                    1112
#define IDC_CHECK_RENAME                1113
#define IDC_QUALITY_DIALOG              1114
#define IDC_CHECK_HOLD                  1115
#define IDC_CHECK_LOOP                  1116
#define IDC_TEXT_KEY                    1117
#define IDC_KEY                         1118
#define IDC_KEY_DRAG                    1119
#define IDC_TEXT_SORT                   1120
#define IDC_COMBO_SORT                  1121
#define IDC_TEXT_SEC_1                  1122
#define IDC_TEXT_SEC_2                  1123
#define IDC_TEXT_SEC_3                  1124
#define IDC_TEXT_ENVELOPE               1126
#define IDC_BUILD                       1127
#define IDC_TEXT_FROM                   1128
#define IDC_TEXT_TO                     1129
#define IDC_TEXT_CHANNEL                1130
#define IDC_LIST1                       1133
#define IDC_TEXT_VOLUMERATE             1134
#define IDC_VOLUME_RATE                 1135
#define IDC_BITMAP1                     1136
#define IDC_BTN_IMG1                    1137
#define IDM_CLOSE                       40000
#define IDM_MAGx1                       40001
#define IDM_MAGx2                       40002
#define IDM_MAGx4                       40003
#define IDM_CONFIG                      40004
#define IDM_VOLUMEDIALOG                40005
#define IDM_PROPERTY                    40006
#define IDM_ABOUT                       40007
#define IDM_OUTPUT_PTVOICE              40008
#define IDM_EXPORT_VOICE                40009
#define IDM_INPORT_VOICE                40010
#define IDM_UNIT                        40011
#define IDM_INITIALIZE                  40012
#define IDM_SAVE                        40013
#define IDM_LOAD_PCM                    40014
#define IDM_SAVE_AS_PCM                 40015
#define IDM_NEW_PCM                     40016
#define IDM_EDIT_PCM                    40017
#define IDM_PCM_QUALITY                 40018
#define IDM_SAVE_AS                     40020
#define IDM_LOAD                        40021
#define IDM_COPY                        40022
#define IDM_QUALITY_DIALOG              40023
#define IDM_TEST                        40024
#define IDM_LOOP                        40026
#define IDM_CLEAR                       40027
#define ID_SETTING_CONVERTVOLUME        40028
#define IDM_CONVERTVOLUME               40029

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40030
#define _APS_NEXT_CONTROL_VALUE         1138
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
