//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script.rc
//
#define IDC_DELETE                      1000
#define IDCANCEL2                       1001
#define IDC_MESSAGE                     1002
#define IDC_CHECK_WAVELOOP              1003
#define IDC_TEXT_ABOUTTITLE             1004
#define IDC_TEXT_BUILDTITLE             1005
#define IDC_ALLUNIT                     1006
#define IDC_REFLECT                     1007
#define IDC_RELOAD                      1008
#define IDC_CHECK_SMOOTH                1009
#define IDC_EXPORT                      1010
#define IDC_TEMPO                       1011
#define IDC_MEAS1                       1012
#define IDC_MEAS2                       1013
#define IDC_NAME                        1014
#define IDC_BEATNUM                     1015
#define IDC_SAMPLESIZE                  1016
#define IDC_MEAS                        1017
#define IDC_MEASNUM                     1018
#define IDC_COMBO_BEAT                  1019
#define IDC_CHECK_BUILD                 1020
#define IDC_SAMPLESEC                   1021
#define IDC_CHECK_LOOP                  1022
#define IDC_STATUS                      1023
#define IDC_CHECK_ADDUNIT               1024
#define IDC_DELAYFREQ                   1025
#define IDC_FROMMEAS1                   1026
#define IDC_FROMMEAS2                   1027
#define IDC_COMBO_FROMUNIT              1028
#define IDC_TOMEAS                      1029
#define IDC_TOCLOCK                     1030
#define IDC_COPYTIME                    1031
#define IDC_COMBO_TOUNIT                1032
#define IDC_BEATCLOCK                   1033
#define IDC_UNITS                       1034
#define IDC_VERSION                     1035
#define IDC_KEYTUNING                   1035
#define IDC_EVENTNUM                    1036
#define IDC_EVENTMAX                    1037
#define IDC_UNITNUM                     1038
#define IDC_UNITMAX                     1039
#define IDC_TEXT_NAME                   1040
#define IDC_WOICENUM                    1041
#define IDC_TEXT_VOICENO                1042
#define IDC_TEXT_TEMPO                  1043
#define IDC_TEXT_KEYTUNING              1043
#define IDC_UNITMAX2                    1044
#define IDC_WOICEMAX                    1045
#define IDC_TEXT_TYPE                   1046
#define IDC_CHK_VELOCITY                1047
#define IDC_TEXT_CHANNEL                1048
#define IDC_TEXT_MEAS                   1049
#define IDC_TEXT_BEAT                   1050
#define IDC_TEXT_MEAS3                  1051
#define IDC_TEXT_MEASNUM                1052
#define IDC_TEXT_UNITS                  1053
#define IDC_TEXT_COPYMEASTITLE          1054
#define IDC_TEXT_FROM                   1055
#define IDC_TEXT_TO                     1056
#define IDC_TEXT_MEAS2                  1057
#define IDC_TEXT_CLOCK                  1058
#define IDC_TEXT_TIME                   1059
#define IDC_TEXT_CPB                    1060
#define IDC_TEXT_COPYNOTETITLE          1061
#define IDC_TEXT_UNIT                   1062
#define IDC_TEXT_UNIT2                  1063
#define IDC_TEXT_VOICE                  1064
#define IDC_TEXT_PROJECTTITLE           1065
#define IDC_TEXT_EVENT                  1066
#define IDC_TEXT_PROPERTYTITLE          1067
#define IDC_TEXT_UNITTITLE              1068
#define IDC_TEXT_STATUS                 1069
#define IDC_TEXT_SURETITLE              1070
#define IDC_TEXT_TOTALSAMPLE            1071
#define IDC_TEXT_EVENTNUM               1072
#define IDC_TEXT_RATE                   1073
#define IDC_TEXT_DEPTH2                 1074
#define IDC_TEXT_DEPTH3                 1075
#define IDC_TEXT_FREQUENCY              1076
#define IDC_DELAYRATE                   1077
#define IDC_TEXT_DELAYTITLE             1078
#define IDC_TEXT_DELETEMEASTITLE        1079
#define IDC_TUNING                      1080
#define IDC_CREATOR                     1081
#define IDC_BASICKEY                    1082
#define IDC_COMBO_DELAYUNIT             1083
#define IDC_TEXT_SCALE                  1084
#define IDC_TEXT_DELAYSCALE             1085
#define IDC_TEXT_BASICKEY               1086
#define IDC_TEXT_TUNING                 1087
#define IDC_TEXT_HEARSELECT             1088
#define IDC_LIST                        1089
#define IDC_DIRECTORYPATH               1090
#define IDC_INFORMATION                 1091
#define IDC_CHECK_SOUND                 1092
#define IDC_FROMBEAT1                   1093
#define IDC_FROMCLOCK1                  1094
#define IDC_FROMBEAT2                   1095
#define IDC_FROMCLOCK2                  1096
#define IDC_TOBEAT                      1097
#define IDC_TEXT_QUALITY                1098
#define IDC_TEXT_GROUP                  1099
#define IDC_PROGRESS                    1100
#define IDC_STOP                        1101
#define IDC_LAYER                       1102
#define IDC_TEXT_TRANSPOSETITLE         1103
#define IDC_TEXT_EVENTVOLUMETITLE       1104
#define IDC_TEXT_VALUE                  1105
#define IDC_TEXT_MIDIDEVICE             1106
#define IDC_SPIN_VALUE                  1107
#define IDC_COMBO_MIDIDEVICE            1108
#define IDC_TEXT_CONFIGTITLE            1109
#define IDC_TEXT_PS                     1110
#define IDC_TEXT_SPS                    1112
#define IDC_TEXT_BUFFER                 1113
#define IDC_BUFFER                      1114
#define IDC_TEXT_SECOND                 1115
#define IDC_COMBO_DEVICE                1116
#define IDC_TEXT_DEVICE                 1117
#define IDC_TEXT_COMMENTTITLE           1118
#define IDC_TEXT_FONT                   1119
#define IDC_GROUP                       1120
#define IDC_COMBO_FONT                  1121
#define IDC_TEXT_STRAINTITLE            1122
#define IDC_TEXT_OVERDRIVETITLE         1123
#define IDC_RATE                        1124
#define IDC_FONT_SAMPLE                 1125
#define IDC_FONTSAMPLE                  1126
#define IDC_COMMENT                     1127
#define IDC_TRANSPOSE                   1128
#define IDC_TIME                        1129
#define IDC_VOLUME                      1130
#define IDC_CHECK_RENAME                1131
#define IDC_CHECK_BEATFIT               1132
#define IDC_TEXT_START                  1133
#define IDC_DEFAULT                     1134
#define IDC_TEXT_END                    1135
#define IDC_BASICKEY_UP                 1136
#define IDC_TEXT_SCOPE                  1137
#define IDC_BASICKEY_DOWN               1138
#define IDC_GATE1                       1139
#define IDC_CUT                         1140
#define IDC_GATE2                       1141
#define IDC_TEXT_GATE1                  1142
#define IDC_TEXT_CUT                    1143
#define IDC_TEXT_GATE2                  1144
#define IDC_AMP                         1145
#define IDC_TEXT_AMP                    1146
#define IDC_TYPE                        1147
#define IDC_PRESS                       1148
#define IDC_TEXT_VOICETITLE             1149
#define IDC_TEXT_PRESS                  1150
#define IDC_TEXT_ADDTITLE               1151
#define IDC_TEXT_ADDUNITTITLE           1152
#define IDC_COMBO_VOICENO               1153
#define IDC_TEXT_INITIALEVENT           1154
#define IDC_COMBO_CHANNEL               1155
#define IDC_COMBO_SPS                   1157
#define IDC_CHECK_UNITMUTE              1158
#define IDC_TEXT_BUILDOPTION            1159
#define IDC_TEXT_SOUNDQUALITY           1160
#define IDC_COMBO_PLAYSCOPE             1161
#define IDC_TEXT_PLAYINFOMATION         1162
#define IDC_TOTALTIME                   1163
#define IDC_LOOPTIME                    1164
#define IDC_TEXT_TOTALTIME              1165
#define IDC_TEXT_SEC1                   1166
#define IDC_TEXT_SEC2                   1167
#define IDC_TEXT_PLAYTIME               1168
#define IDC_PLAYTIME                    1169
#define IDC_TEXT_SEC3                   1170
#define IDC_TEXT_EXTRAFADE              1171
#define IDC_TEXT_PLAYSCOPE              1172
#define IDC_TEXT_LOOPTIME               1173
#define IDC_EXTRAFADE                   1174
#define IDC_TEXT_KEY                    1175
#define IDC_TOTALTIME2                  1176
#define IDC_TEXT_SEC4                   1177
#define IDC_TEXT_SORT                   1178
#define IDC_TEXT_LOOPTIME2              1179
#define IDC_TEXT_HEADTIME               1180
#define IDC_KEY                         1181
#define IDC_HEADTIME                    1182
#define IDC_KEY2                        1183
#define IDC_TEXT_SEC5                   1184
#define IDC_KEY_DRAG                    1185
#define IDC_TEXT_PLAYTIME2              1186
#define IDC_CHECK_EVENT_ON              1187
#define IDC_TEXT_PLAYTIME3              1188
#define IDC_CHECK_EVENT_PAN_VOLUME      1189
#define IDC_CHECK_EVENT_VOLUME          1190
#define IDC_CHECK_EVENT_PORTAMENT       1191
#define IDC_CHECK_EVENT_VOICENO         1192
#define IDC_CHECK_EVENT_GROUPNO         1193
#define IDC_CHECK_EVENT_TUNING          1194
#define IDC_CHECK_EVENT_KEY             1195
#define IDC_COMBO_SORT                  1196
#define IDC_CHECK_EVENT_PAN_TIME        1197
#define IDC_BEAT_DIVIDE                 1198
#define IDC_BEAT_DIVIDE2                1199
#define IDC_BEAT_TEMPO                  1200
#define IDC_RESULT_WAIT                 1201
#define IDC_RESULT_TEMPO                1202
#define IDM_ARRANGE_TILE                40000
#define IDM_CLOSE                       40001
#define IDM_VERSION                     40002
#define IDM_ABOUT                       40003
#define IDM_TEST                        40004
#define IDM_READWAVE                    40005
#define IDM_CONVERTWAVE_STEREO          40006
#define IDM_CONVERTWAVE_MONO            40007
#define IDM_CONVERTWAVE_16BIT           40008
#define IDM_CONVERTWAVE_8BIT            40009
#define IDM_CONVERTWAVE_44KHZ           40010
#define IDM_CONVERTWAVE_22KHZ           40011
#define IDM_CONVERTWAVE_11KHZ           40012
#define IDM_ADDUNIT_FILE                40013
#define IDM_DELETEUNIT                  40014
#define IDM_REMOVEUNIT                  40015
#define IDM_LOADPROJECT                 40016
#define IDM_SAVEPROJECT                 40017
#define IDM_OPTION                      40018
#define IDM_COPYUNIT                    40019
#define IDM_EDITUNIT                    40020
#define IDM_INITPROJECT                 40021
#define IDM_EDITPROJECT                 40022
#define IDM_COPYNOTE                    40023
#define IDM_COPYMEAS                    40024
#define IDM_PROPERTY                    40025
#define IDM_SELECTALLUNIT               40026
#define IDM_SAVEPROJECTAS               40027
#define IDM_STOPBUILD                   40028
#define IDM_DELETEMEAS                  40029
#define IDM_UNDOEVENT                   40030
#define IDM_REDOEVENT                   40031
#define IDM_OUTPUTEVENTS                40032
#define IDM_BUILDAS                     40033
#define IDM_VOLUMEDIALOG                40034
#define IDM_TRANSPOSE                   40035
#define IDM_CONFIG                      40036
#define IDM_COMMENT                     40037
#define IDM_OUTPUTTUNE                  40038
#define IDM_DELAY_1                     40039
#define IDM_DELAY_0                     40040
#define IDM_STRAIN_1                    40041
#define IDM_STRAIN_0                    40042
#define IDM_VELOCITY                    40043
#define IDM_VOLUME                      40044
#define IDM_SCOPE                       40045
#define IDM_HISTORY_D                   40046
#define ID_FILE_                        40047
#define ID_FILE_HISTORY                 40047
#define IDM_HISTORY_0                   40047
#define IDM_HISTORY_1                   40048
#define IDM_HISTORY_2                   40049
#define IDM_HISTORY_3                   40050
#define IDM_HISTORY_4                   40051
#define IDM_HISTORY_5                   40052
#define IDM_HISTORY_6                   40053
#define IDM_HISTORY_7                   40054
#define IDM_HISTORY_8                   40055
#define IDM_HISTORY_9                   40056
#define IDM_PAN_VOLUME                  40057
#define IDM_PAN_TIME                    40058
#define IDM_OUTPUT_PTI                  40059
#define IDM_HISTORY_10                  40060
#define IDM_HISTORY_11                  40061
#define IDM_HISTORY_12                  40062
#define IDM_HISTORY_13                  40063
#define IDM_HISTORY_14                  40064
#define IDM_HISTORY_15                  40065
#define IDM_HISTORY_16                  40066
#define IDM_HISTORY_17                  40067
#define IDM_HISTORY_18                  40068
#define IDM_HISTORY_19                  40069
#define IDM_CONVERTWAVE_48KHZ           40070
#define ID_CONVERT_48000HZ              40073

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         40071
#define _APS_NEXT_CONTROL_VALUE         1203
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
